### ISSUE TITLE
Swift usage

### ISSUE THREAD

**Issue by Stan92** [danny-source/DYAlertPickerViewDemo#1]
Hi, 
I'm trying to use your library with Swift.
I add the header file within my bridge file but I get an error in the following methods
  func DYAlertPickView(pickerView: DYAlertPickView!, titleForRow row: Int) -> NSAttributedString! 
 func numberOfRowsInDYAlertPickerView(pickerView: DYAlertPickView!) -> Int
etc...
saying Use of undeclared type 'DYAlertPickView'

**Comment by danny-source** [comment]
it's bug ,i will fix it later.
delegate i am not follow coca pattern,it have problem

**Comment by danny-source** [comment]
i will fix later

**Comment by Stan92** [comment]
I thank you in advance.

**Comment by danny-source** [comment]
i was solved about objective-c bridging swift and add Swift Demo.
you can clone new release to test
